QT.3drenderer_private.VERSION = 5.5.1
QT.3drenderer_private.MAJOR_VERSION = 5
QT.3drenderer_private.MINOR_VERSION = 5
QT.3drenderer_private.PATCH_VERSION = 1
QT.3drenderer_private.name = Qt3DRenderer
QT.3drenderer_private.libs = $$QT_MODULE_LIB_BASE
QT.3drenderer_private.includes = $$QT_MODULE_INCLUDE_BASE/Qt3DRenderer/5.5.1 $$QT_MODULE_INCLUDE_BASE/Qt3DRenderer/5.5.1/Qt3DRenderer
QT.3drenderer_private.depends = 3drenderer
QT.3drenderer_private.module_config = internal_module no_link
