QT.3dinput_private.VERSION = 5.5.1
QT.3dinput_private.MAJOR_VERSION = 5
QT.3dinput_private.MINOR_VERSION = 5
QT.3dinput_private.PATCH_VERSION = 1
QT.3dinput_private.name = Qt3DInput
QT.3dinput_private.libs = $$QT_MODULE_LIB_BASE
QT.3dinput_private.includes = $$QT_MODULE_INCLUDE_BASE/Qt3DInput/5.5.1 $$QT_MODULE_INCLUDE_BASE/Qt3DInput/5.5.1/Qt3DInput
QT.3dinput_private.depends = 3dinput
QT.3dinput_private.module_config = internal_module no_link
