QT.androidextras_private.VERSION = 5.5.1
QT.androidextras_private.MAJOR_VERSION = 5
QT.androidextras_private.MINOR_VERSION = 5
QT.androidextras_private.PATCH_VERSION = 1
QT.androidextras_private.name = QtAndroidExtras
QT.androidextras_private.libs = $$QT_MODULE_LIB_BASE
QT.androidextras_private.includes = $$QT_MODULE_INCLUDE_BASE/QtAndroidExtras/5.5.1 $$QT_MODULE_INCLUDE_BASE/QtAndroidExtras/5.5.1/QtAndroidExtras
QT.androidextras_private.depends = androidextras
QT.androidextras_private.module_config = internal_module no_link
