QT.3dcollision_private.VERSION = 5.5.1
QT.3dcollision_private.MAJOR_VERSION = 5
QT.3dcollision_private.MINOR_VERSION = 5
QT.3dcollision_private.PATCH_VERSION = 1
QT.3dcollision_private.name = Qt3DCollision
QT.3dcollision_private.libs = $$QT_MODULE_LIB_BASE
QT.3dcollision_private.includes = $$QT_MODULE_INCLUDE_BASE/Qt3DCollision/5.5.1 $$QT_MODULE_INCLUDE_BASE/Qt3DCollision/5.5.1/Qt3DCollision
QT.3dcollision_private.depends = 3dcollision
QT.3dcollision_private.module_config = internal_module no_link
