QT.3dquick_private.VERSION = 5.5.1
QT.3dquick_private.MAJOR_VERSION = 5
QT.3dquick_private.MINOR_VERSION = 5
QT.3dquick_private.PATCH_VERSION = 1
QT.3dquick_private.name = Qt3DQuick
QT.3dquick_private.libs = $$QT_MODULE_LIB_BASE
QT.3dquick_private.includes = $$QT_MODULE_INCLUDE_BASE/Qt3DQuick/5.5.1 $$QT_MODULE_INCLUDE_BASE/Qt3DQuick/5.5.1/Qt3DQuick
QT.3dquick_private.depends = 3dquick
QT.3dquick_private.module_config = internal_module no_link
